# Generated by Django 3.0.2 on 2020-02-09 11:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200205_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='dateAvailable',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='lisitngs/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='lisitngs/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image4',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='lisitngs/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image5',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='lisitngs/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='postalCode',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
