# Generated by Django 3.0.2 on 2020-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200209_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='neighbourhood',
            field=models.CharField(default='Leslieville', max_length=25),
            preserve_default=False,
        ),
    ]
